added some legendary quotes
jmike/famous-last-words pull request #4
Opened 2018-10-15 19:27 UTC by cherouvim

2018-10-15 20:20 UTC, Return-1 commented on src/index.js
> +  'Hurry up. This is just a proof of concept.',
I think this one is similar to the one above. Otherwise its all good with me. @jmike ?

2018-10-16 09:52 UTC, jmike requested changes
Awesome stuff. A couple of comments on my side.

2018-10-16 09:52 UTC, jmike commented on src/index.js
> +  'Hurry up. This is just a proof of concept.',
Agreed, @cherouvim line #15 is quite similar to line #14.
Would you agree to remove it from the PR?

2018-10-16 09:52 UTC, jmike commented on src/index.js
> +  'Can we worry about security at a later phase?'
@cherouvim suggestion to simplify: "Can we worry about security later?"

What do you think?

2018-10-16 10:30 UTC, cherouvim reviewed
Requested changes done.

2018-10-16 10:30 UTC, cherouvim commented on src/index.js
> +  'Hurry up. This is just a proof of concept.',
Done.

2018-10-16 10:30 UTC, cherouvim commented on src/index.js
> +  'Can we worry about security at a later phase?'
Done.

2018-10-17 06:37 UTC, jmike approved these changes

2018-10-17 06:52 UTC, jmike commented
Accepted and merged manually.

2018-10-17 06:52 UTC, closed without merging